import type { NextPage } from 'next'
import Link from "next/link"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/AboutMe.module.scss'

const AboutMe: NextPage = () => {
  return (
    <div className={styles.container }>
        <div className={styles.banner}>
            Hover over a card to learn more
            </div>
      <Head>
        <title>Jordan de Souza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.card} style={{marginRight: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
              Waterloo Computer Engineering with AI option
          </div>
          <div className={styles.description}>
              I am will be going into my 3rd year for computer engineering at the University of Waterloo, and I am pursuing an Artificial Intelligence option as part of my degree
          </div>
        </div>
        <div className={styles.card} style={{marginLeft: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
              Software developer
          </div>
          <div className={styles.description}>
              I have 2 years of professional experience, and 5 years of general experience with software development. Head over to the work experience section of my site to find out more specifics
          </div>
        </div>
        <div className={styles.card} style={{marginRight: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
              Professional Musician
          </div>
          <div className={styles.description}>
          I specialize in the various types of Saxophones and Piano, but I
              play the Drums, Flute, and Trumpet as well.
              <br /> I have played at various concert venues across North
              America and won several first place titles in jazz festivals and chamber choir  competitions 
          </div>
        </div>
        <div className={styles.card} style={{marginLeft: "30%", marginTop:"10%"}}>
        <div className={styles.title}>
            Looking for an Internship
          </div>
          <div className={styles.description}>
            I am currently looking for a coop position for winter 2022,
              starting in January. If you have, or know of, any positions,
              please contact me through email at jordandesouza5@gmail.com. My resume can be found by clicking on the resume card on my home page</div>
        </div>
    </div>
  )
}

export default AboutMe 
