import type { NextPage } from 'next'
import Link from "next/link"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/ContactMe.module.scss'

const ContactMe: NextPage = () => {
  return (
    <div className={styles.container }>
        <div className={styles.banner}>
            Hover over a card to learn more
            </div>
      <Head>
        <title>Jordan de Souza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="../public/fonts/AvenirNextLTPro-It.otf"
          as="font"
          crossOrigin=""
          />
        <link
          rel="preload"
          href="../public/fonts/AvenirNextLTPro-Regular.otf"
          as="font"
          crossOrigin=""
          />
        <link
          rel="preload"
          href="../public/fonts/AvenirNextLTPro-Bold.otf"
          as="font"
          crossOrigin=""
          />
      </Head>
      <div className={styles.FlexRow}>
          <a href="https://github.com/jordandde">
        <div className={styles.card}>
          <div className={styles.title}>
              Github
          </div>
          <div className={styles.description}>
              Click on this card to get to my github
          </div>
        </div>
          </a>
          <a href="https://linkedin.com/in/jordandde">
        <div className={styles.card}>
          <div className={styles.title}>
              Linkedin
          </div>
          <div className={styles.description}>
              Click on this card to get to my linkedin
          </div>
        </div>
        </a>
        </div>
        <div className={styles.FlexRow}>
          <a href="mailto:jordandesouza5@gmail.com?subject=Hello">
        <div className={styles.card}>
          <div className={styles.title}>
                Email 
          </div>
          <div className={styles.description}>
                Click on this card to bring up my email
          </div>
        </div>
          </a>
          <a href="https://drive.google.com/file/d/18jCY7sc8aV-m0LwhFrKtjG6ip8oj5stc/view?usp=sharing">
        <div className={styles.card}>
          <div className={styles.title}>
              Resume
          </div>
          <div className={styles.description}>
              Click on this card to get to my Resume
          </div>
        </div>
        </a>
        </div>
    </div>
  )
}

export default ContactMe 
