import type { NextPage } from 'next'
import Link from "next/link"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Experience.module.scss'

const Experience: NextPage = () => {
  return (
    <div className={styles.container }>
        <div className={styles.banner}>
            Hover over a card to learn more
            </div>
      <Head>
        <title>Jordan de Souza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.card} style={{marginRight: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
              OpenText <br/>Frontend Developer <br/>05/21 - 09/21 <br/> Nextjs, SCSS, Typescript, Rust, WASM
          </div>
          <div className={styles.description}>
              At OpenText I worked as a frontend developer. Over the course of the term I greatly expanded the in-house SCSS library by developing and updating over 60 reuseable SCSS components.
              In addition to that I presented the changes I made to the various users of the library, and recorded the presentation so that future users will have a reference for anything they need to use from the library.
              I also worked on the SLA reminder system, and implemented Redux in the reminder application so that we could store information more reliably. Finally, I led a team and created a collaborative text editor using Rust, Wasm and React
          </div>
        </div>
        <div className={styles.card} style={{marginLeft: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
              Bitback <br/>Backend Developer <br/>09/20 - 12/20 <br /> Go, PostgreSQL, Amazon S3
          </div>
          <div className={styles.description}>
              At Bitback I worked as a backend developer. One of the more notable contributions I made to the company was that I developed a CLI in Go using the cobra library to allow the admin users to interface with the PostgreSQL database without needing to access the database.
              I also developed an event storing system that takes events from the various queues and uploaded them to s3 buckets for more visibility. Finally, I went through all of the existing queries and rewrote them, and restructured the database, to vastly improve the database&apos;s response time.
          </div>
        </div>
        <div className={styles.card} style={{marginRight: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
              Professional Musician
          </div>
          <div className={styles.description}>
          I specialize in the various types of Saxophones and Piano, but I
              play the Drums, Flute, and Trumpet as well.
              <br /> I have played at various concert venues across North
              America and won several first place titles in jazz festivals and chamber choir  competitions 
          </div>
        </div>
        <div className={styles.card} style={{marginLeft: "30%", marginTop:"10%"}}>
        <div className={styles.title}>
            Looking for an Internship
          </div>
          <div className={styles.description}>
            I am currently looking for a coop position for winter 2022,
              starting in January. If you have, or know of, any positions,
              please contact me through email at jordandesouza5@gmail.com. My resume can be found by clicking on the resume card on my home page</div>
        </div>
    </div>
  )
}

export default Experience 
