import type { NextPage } from 'next'
import Link from "next/link"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Experience.module.scss'

const Experience: NextPage = () => {
  return (
    <div className={styles.container }>
        <div className={styles.banner}>
            Hover over a card to learn more
            </div>
      <Head>
        <title>Jordan de Souza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="../public/fonts/AvenirNextLTPro-It.otf"
          as="font"
          crossOrigin=""
          />
        <link
          rel="preload"
          href="../public/fonts/AvenirNextLTPro-Regular.otf"
          as="font"
          crossOrigin=""
          />
        <link
          rel="preload"
          href="../public/fonts/AvenirNextLTPro-Bold.otf"
          as="font"
          crossOrigin=""
          />
      </Head>
        <div className={styles.card} style={{marginRight: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
              OpenText <br/>Frontend Developer <br/>05/21 - 09/21 <br/> Nextjs, SCSS, Typescript, Rust, WASM, Redux
          </div>
          <div className={styles.description}>
              At OpenText I worked as a frontend developer. Over the course of the term I greatly expanded the in-house SCSS library by developing and updating over 60 reuseable SCSS components.
              In addition to that I presented the changes I made to the various users of the library, and recorded the presentation so that future users will have a reference for anything they need to use from the library.
              I also worked on the SLA reminder system, and implemented Redux in the reminder application so that we could store information more reliably. Finally, I led a team and created a collaborative text editor using Rust, Wasm and React
          </div>
        </div>
        <div className={styles.card} style={{marginLeft: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
              Bitback <br/>Backend Developer <br/>09/20 - 12/20 <br /> Go, PostgreSQL, Amazon S3
          </div>
          <div className={styles.description}>
              At Bitback I worked as a backend developer. One of the more notable contributions I made to the company was that I developed a CLI in Go using the cobra library to allow the admin users to interface with the PostgreSQL database without needing to access the database.
              I also developed an event storing system that takes events from the various queues and uploaded them to s3 buckets for more visibility. Finally, I went through all of the existing queries and rewrote them, and restructured the database, to vastly improve the database&apos;s response time.
          </div>
        </div>
        <div className={styles.card} style={{marginRight: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
              IBM <br/>Backend Developer <br/>01/20 - 04/20 <br/> Go, Ansible, NodeJS, Python, Kubernetes, REST APIs
          </div>
          <div className={styles.description}>
            At IBM I worked as a backend developer. Over the term, I worked on a REST API, in Go, that was used to interface with the IBM cloud
            and return information on the portals that were being hosted there. This API also allowed for the creation and deletion of portals
             and proved to be especially useful for rebooting portals that would often fail. I also worked on the CLI. The CLI was written in Go and
              had a terrible run time for all of it&apos;s applications due to needing to parse large chunks of data. Seeing this, I implemented multithreading
              in the CLI by utilizing Goroutines and managed to reduce the average run time for the commands in the CLI from 60 seconds to 5 seconds without placing 
              any noticeable stress on the machiene. Finally, I worked on updating the packages on the IBM remote servers, and added new packages to the servers. To orchestrate this,
              I utilized Ansible and wrote the playbooks myself.
          </div>
        </div>
        <div className={styles.card} style={{marginLeft: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
              Tugolo <br/>Fullstack Developer <br/>05/19 - 08/19 <br /> Go, PostgreSQL, ReactJS, Redux 
          </div>
          <div className={styles.description}>
            At Tugolo I worked as a fullstack developer. During the term, I was in charge of a lot of projects. My first one was to develop an internal React app that would allow admin users to accept or deny a seller from a list of sellers that wanted to offer their services on our site. After a decision was clicked on, the seller would be automatically emailed with the decision.
            The next thing that I worked on is a password recovery system. Written in Go, the system takes in a user&apos;s email, queries the database, and emails the user if the key is in the database. This let the user reset the password, which would be replaced in the database.
            Finally I worked on designing and developing a product review system with a Go backend and React frontend that used Redux for state manipulation. It allowed users to review items and would store the reviews in a PostgreSQL database. All reviews would be returned, paginated, when a user navigated to a product page and there are several filters that could be used to search for reviews. This relied simply on regex.
          </div>
        </div>
    </div>
  )
}

export default Experience 
