import type { NextPage } from 'next'
import Link from "next/link"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container }>
      <Head>
        <title>Jordan de Souza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div 
        style={{height:"100vh"}}>
        <div 
        className={styles.FlexRow}
            style={{ height: "100%", justifyContent: "center", color: "#c3acce" }}
          >
            <div
            className={styles.FlexCol}
              style={{
                paddingRight: 30
              }}
            >
              <div className={styles.sticky_banner}>Hi, I&apos;m</div>
            </div>
            <div className={styles.FlexCol}>
              <div className={styles.sticky_banner}>Jord</div>
            </div>
            <div className={styles.FlexCol}>
              <div className={styles.sticky_banner} style={{ position: "relative" }}>an</div>
              <div className={styles.sticky_banner}>and</div>
            </div>
            <div className={styles.FlexCol}>
              <div className={styles.sticky_banner}
                style={{
                  marginTop: "19vh",
                  position: "relative"
                }}
              >
                rew
              </div>
              <div className={styles.sticky_banner}>de</div>
            </div>
            <div className={styles.FlexCol}>
              <div className={styles.sticky_banner} style={{ marginTop: "38vh", position: "relative" }}>
                Souza
              </div>
              <div className={styles.sticky_banner} />
            </div>
          </div>
        </div>
        <Link href="/AboutMe" passHref>
        <div className={styles.card} style={{marginRight: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
            About Me
          </div>
          <div className={styles.description}>
            Click to find out more about me, such as: my current school, job status, and background 
          </div>
        </div>
        </Link>
        <Link href="/Experience" passHref>
        <div className={styles.card} style={{marginLeft: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
            Work Experience
          </div>
          <div className={styles.description}>
            Click to find out more about my work history and professional experience
          </div>
        </div>
        </Link>
        <Link href="Skills" passHref>
        <div className={styles.card} style={{marginRight: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
            Skills and Interests
          </div>
          <div className={styles.description}>
              Click to find out more about my skills, such as my proficient languages, and preferred technology
          </div>
        </div>
        </Link>
        <div className={styles.card} style={{marginLeft: "30%", marginTop:"10%"}}>Resume</div>
    </div>
  )
}

export default Home
