import type { NextPage } from 'next'
import Link from "next/link"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/AboutMe.module.scss'

const AboutMe: NextPage = () => {
  return (
    <div className={styles.container }>
      <Head>
        <title>Jordan de Souza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="../public/fonts/AvenirNextLTPro-It.otf"
          as="font"
          crossOrigin=""
          />
        <link
          rel="preload"
          href="../public/fonts/AvenirNextLTPro-Regular.otf"
          as="font"
          crossOrigin=""
          />
        <link
          rel="preload"
          href="../public/fonts/AvenirNextLTPro-Bold.otf"
          as="font"
          crossOrigin=""
          />
      </Head>
        <div className={styles.card} style={{marginRight: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
            About Me
          </div>
          <div className={styles.description}>
            Click to find out more about me, such as: my current school, job status, and background 
          </div>
        </div>
        <div className={styles.card} style={{marginLeft: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
            Work Experience
          </div>
          <div className={styles.description}>
            Click to find out more about my work history and professional experience
          </div>
        </div>
        <div className={styles.card} style={{marginRight: "30%", marginTop:"10%"}}>
          <div className={styles.title}>
            Skills and Interests
          </div>
          <div className={styles.description}>
              Click to find out more about my skills, such as my proficient languages, and preferred technology
          </div>
        </div>
        <div className={styles.card} style={{marginLeft: "30%", marginTop:"10%"}}>Resume</div>
    </div>
  )
}

export default AboutMe 
